version: "3"
services:
  time2do-db:
    image: mysql:8.0
    container_name: time2do-mysql
    ports:
      - 33336:3306
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.data
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
