version: "3"
services:
  time2do-db:
    image: mysql:8.0
    container_name: time2do-mysql
    ports:
      - "33336:3306"
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      TZ: Asia/Seoul
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.data
      - ./mysql/data:/var/lib/mysql
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  time2do-go:
      image: golang:1.20
      container_name: time2do-go
      build:
        context: .
      depends_on:
        - time2do-db
      environment:
        MYSQL_HOST: "time2do-db"
        MYSQL_PORT: "${MYSQL_PORT}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}" 
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
      ports:
        - "8888:8888"
      expose:
        - "8888"
      # restart: always
  time2do-react:
  