basePath: /
definitions:
  controller.UserCommand:
    properties:
      password:
        type: string
      userName:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is a sample serice for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /group:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 타이머 생성하기
  /groups:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 그룹 조회하기
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.UserCommand'
      produces:
      - application/json
      responses: {}
      summary: User Login
  /task:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 할일 생성하기
  /tasks:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 아무 조건 없이 모든 ToDo 불러오기
  /user:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 유저 생성하기
  /user/{id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 유저 ID 로 조회하기
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 아무 조건 없이 모든 User 불러오기
swagger: "2.0"
