basePath: /
host: localhost:8888
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is a sample serice for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 유저 생성하기
      tags:
      - user
  /user/{id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 유저 ID 로 조회하기
      tags:
      - user
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 모든 유저 정보 모두 불러오기
      tags:
      - user
swagger: "2.0"
