basePath: /
definitions:
  controller.CreateUserCommand:
    properties:
      password:
        type: string
      userName:
        type: string
    type: object
  controller.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  controller.UserCommand:
    properties:
      password:
        type: string
      userName:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: devgunho@gmail.com
    name: API Support
  description: This is Time2Do API Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Time2Do API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserCommand'
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controller.ErrorResponse'
      summary: 유저 로그인
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.CreateUserCommand'
      produces:
      - application/json
      responses: {}
      summary: 유저 생성
swagger: "2.0"
